name: Rust

on:
  push:
    branches: ['master', 'release']
  pull_request:
    branches: ['master']

env:
  CARGO_TERM_COLOR: always

jobs:
  build-radar-web:
    name: Radar Web Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
          cache-dependency-path: |
            radar/web/yarn.lock
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: radar/web
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: radar/web
        env:
          NODE_ENV: production
      - uses: actions/upload-artifact@v4
        name: Upload
        with:
          name: radar-www
          path: radar/web/dist

  build-radar-server:
    name: Radar Server (${{ matrix.build }})
    strategy:
      matrix:
        build: [linux, windows]
        include:
          - build: linux
            os: ubuntu-20.04
            target: radar-server-standalone
            # https://github.com/clap-rs/clap/issues/1938#issuecomment-632186396
            flags: ''

          - build: windows
            os: windows-latest
            target: radar-server-standalone.exe
            flags: -Ctarget-feature=+crt-static

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Build
        run: cargo build --verbose --release --bin radar-server-standalone
        env:
          RUSTFLAGS: ${{ matrix.flags }}
      - uses: actions/upload-artifact@v4
        name: Upload radar server
        with:
          name: radar-server-${{ matrix.build }}
          path: target/release/${{ matrix.target }}

  build-radar-client:
    name: Radar Client
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Valthrun Rust
        run: .github\workflows\vt-rustc-setup.ps1
        env:
          VT_RUSTC: ${{ vars.VT_RUSTC }}
          VT_RUSTC_AUTHORIZATION: ${{ secrets.VT_RUSTC_AUTHORIZATION }}

      - name: Get package version
        shell: bash
        run: |
          VERSION=$(cargo pkgid --manifest-path radar/client-standalone/Cargo.toml | cut -d# -f2 | cut -d: -f2 | cut -d@ -f2)
          echo "Package version: $VERSION"
          echo "ARTIFACT_VERSION=$VERSION" >> "$GITHUB_ENV"

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build
        run: cargo build --verbose --release --bin radar-client-standalone
        env:
          RUSTFLAGS: -Ctarget-feature=+crt-static

      - name: Upload release build to portal
        shell: bash
        run: .github/workflows/artifact_upload.sh cs2-radar-client target/release/radar-client-standalone.exe target/release/radar_client_standalone.pdb
        if: ${{ github.event_name != 'pull_request' }}
        env:
          ARTIFACT_API_KEY: ${{ secrets.ARTIFACT_API_KEY }}

  build-overlay:
    name: CS2 Overlay
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Valthrun Rust
        run: .github\workflows\vt-rustc-setup.ps1
        env:
          VT_RUSTC: ${{ vars.VT_RUSTC }}
          VT_RUSTC_AUTHORIZATION: ${{ secrets.VT_RUSTC_AUTHORIZATION }}

      - name: Get package version
        shell: bash
        run: |
          VERSION=$(cargo pkgid --manifest-path controller/Cargo.toml | cut -d# -f2 | cut -d: -f2)
          echo "Package version: $VERSION"
          echo "ARTIFACT_VERSION=$VERSION" >> "$GITHUB_ENV"

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build
        run: cargo build --verbose --release --bin controller
        env:
          RUSTFLAGS: -Ctarget-feature=+crt-static

      # Right now there are no tests specified
      # - name: Run tests
      #   run: cargo test --verbose

      - name: Upload release build to portal
        shell: bash
        run: .github/workflows/artifact_upload.sh cs2-overlay target/release/controller.exe target/release/controller.pdb
        if: ${{ github.event_name != 'pull_request' }}
        env:
          ARTIFACT_API_KEY: ${{ secrets.ARTIFACT_API_KEY }}

  build-schema-dump:
    name: CS2 Schema Dumper
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Valthrun Rust
        run: .github\workflows\vt-rustc-setup.ps1
        env:
          VT_RUSTC: ${{ vars.VT_RUSTC }}
          VT_RUSTC_AUTHORIZATION: ${{ secrets.VT_RUSTC_AUTHORIZATION }}

      - name: Get package version
        shell: bash
        run: |
          VERSION=$(cargo pkgid --manifest-path cs2-schema/dumper/Cargo.toml | cut -d# -f2 | cut -d: -f2)
          echo "Package version: $VERSION"
          echo "ARTIFACT_VERSION=$VERSION" >> "$GITHUB_ENV"

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build
        run: cargo build --verbose --release --bin cs2-schema-dumper
        env:
          RUSTFLAGS: -Ctarget-feature=+crt-static

      - name: Upload release build to portal
        shell: bash
        run: .github/workflows/artifact_upload.sh cs2-schema-dumper target/release/cs2-schema-dumper.exe target/release/cs2_schema_dumper.pdb
        if: ${{ github.event_name != 'pull_request' }}
        env:
          ARTIFACT_API_KEY: ${{ secrets.ARTIFACT_API_KEY }}

  Release:
    needs: [ build-radar-web, build-radar-server, build-radar-client, build-overlay, build-schema-dump ]
    runs-on: ubuntu-latest
    env:
      Release_DIR: /home/runner/work/release
    steps:

      - name: Set current time
        id: set_time
        run: echo "time=$(date + '%Y-%m-%d_%H-%M-%S')" >> "$GITHUB_OUTPUT"

      - name: Generate release tag
        id: tag
        run: |
          echo "release_tag=$(date +"%Y%m%d_%H-%M-%S")" >> $GITHUB_OUTPUT
          touch release.txt
          echo "Commit Message:" >> release.txt
          echo "${{ github.event.workflow_run.head_commit.message }}" >> release.txt
          echo "Build Date: $(date +"%Y/%m/%d")" >> release.txt
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ env.Release_DIR }}

      - name: Zip radar server assets
        run: zip -r ${{ env.Release_DIR }}/radar-www/radar-www.zip ${{ env.Release_DIR }}/radar-www

      - name: Rename artifacts
        run: |
          mv ${{ env.Release_DIR }}/radar-server-linux/radar-server-standalone ${{ env.Release_DIR }}/radar-server-linux/radar-server-standalone-linux
          mv ${{ env.Release_DIR }}/radar-server-windows/radar-server-standalone.exe ${{ env.Release_DIR }}/radar-server-windows/radar-server-standalone-windows.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v.${{ steps.tag.outputs.release_tag }}
          name: ${{ steps.tag.outputs.release_tag }} Valthrun
          body_path: release.txt
          files: |
            ${{ env.Release_DIR }}/cs2_overlay/controller.exe
            ${{ env.Release_DIR }}/radar-server-linux/radar-server-standalone-linux
            ${{ env.Release_DIR }}/radar-server-windows/radar-server-standalone-windows.exe
            ${{ env.Release_DIR }}/radar_client_standalone/radar-client-standalone.exe
            ${{ env.Release_DIR }}/radar-www/radar-www.zip
